import { ProfileApiResponse } from "./types";

export const mockProfileData: ProfileApiResponse = {
  profile: {
    profileId: 29,
    userId: 28,
    studentCode: "22130027",
    fullName: "Huynh Minh Nam",
    gender: "female",
    ageGroup: "0-35",
    region: "Khanh Hoa",
    cohort: {
      cohortId: 1,
      cohortCode: "48",
      startAcademicYear: 2022,
      totalStudyYears: 4,
      curriculum: {
        curriculumId: 1,
        curriculumCode: "CTDT_K48_CNTT",
        curriculumName: "Chuong trinh dao tao CNTT khoa 48 (bat dau 2022)",
      },
    },
    createdAt: "2026-04-09T16:38:55",
  },
  termProfiles: [
    {
      id: 29,
      userId: 28,
      term: {
        termId: 8,
        academicYearStart: 2025,
        academicYearEnd: 2026,
        semesterNo: 2,
        fullName: "Hoc ky 2 - Nam hoc 2025 - 2026",
        status: "active",
      },
      studyYearNo: 4,
      semesterNo: 2,
      avgScore: 8.36,
      studiedCredits: 125,
      studyGoal: "High Achiever",
      studyMode: "mutual_support",
      mainSubjectId: 62,
      mainSubjectName: "Chuyen de WEB",
    },
  ],
  enrollments: [
    {
      enrollmentId: 113,
      subject: {
        subjectId: 61,
        subjectCode: "214290",
        subjectName: "IoT",
      },
      term: {
        termId: 8,
        academicYearStart: 2025,
        academicYearEnd: 2026,
        semesterNo: 2,
        fullName: "Hoc ky 2 - Nam hoc 2025 - 2026",
        status: "active",
      },
    },
    {
      enrollmentId: 110,
      subject: {
        subjectId: 64,
        subjectCode: "214483",
        subjectName: "Thuong mai dien tu",
      },
      term: {
        termId: 8,
        academicYearStart: 2025,
        academicYearEnd: 2026,
        semesterNo: 2,
        fullName: "Hoc ky 2 - Nam hoc 2025 - 2026",
        status: "active",
      },
    },
    {
      enrollmentId: 112,
      subject: {
        subjectId: 66,
        subjectCode: "214987",
        subjectName: "Khoa luan tot nghiep",
      },
      term: {
        termId: 8,
        academicYearStart: 2025,
        academicYearEnd: 2026,
        semesterNo: 2,
        fullName: "Hoc ky 2 - Nam hoc 2025 - 2026",
        status: "active",
      },
    },
    {
      enrollmentId: 111,
      subject: {
        subjectId: 67,
        subjectCode: "214988",
        subjectName: "Tieu luan tot nghiep",
      },
      term: {
        termId: 8,
        academicYearStart: 2025,
        academicYearEnd: 2026,
        semesterNo: 2,
        fullName: "Hoc ky 2 - Nam hoc 2025 - 2026",
        status: "active",
      },
    },
  ],
  freeTimeSlots: [
    { id: 264, dayOfWeek: 0, slotCode: "ca3", isAvailable: true },
    { id: 266, dayOfWeek: 1, slotCode: "ca6", isAvailable: true },
    { id: 259, dayOfWeek: 2, slotCode: "ca6", isAvailable: true },
    { id: 262, dayOfWeek: 3, slotCode: "ca3", isAvailable: true },
    { id: 260, dayOfWeek: 3, slotCode: "ca6", isAvailable: true },
    { id: 265, dayOfWeek: 4, slotCode: "ca1", isAvailable: true },
    { id: 263, dayOfWeek: 4, slotCode: "ca3", isAvailable: true },
    { id: 261, dayOfWeek: 5, slotCode: "ca5", isAvailable: true },
    { id: 267, dayOfWeek: 6, slotCode: "ca4", isAvailable: true },
  ],
  scheduleSlots: [
    {
      id: 221,
      subject: { subjectId: 61, subjectCode: "214290", subjectName: "IoT" },
      dayOfWeek: 0,
      slotCode: "ca2",
      scheduleType: "CURRENT_TERM",
      location: null,
      note: null,
    },
    {
      id: 215,
      subject: {
        subjectId: 62,
        subjectCode: "214374",
        subjectName: "Chuyen de WEB",
      },
      dayOfWeek: 1,
      slotCode: "ca3",
      scheduleType: "MAIN_SUBJECT",
      location: null,
      note: null,
    },
    {
      id: 214,
      subject: {
        subjectId: 62,
        subjectCode: "214374",
        subjectName: "Chuyen de WEB",
      },
      dayOfWeek: 5,
      slotCode: "ca6",
      scheduleType: "MAIN_SUBJECT",
      location: null,
      note: null,
    },
    {
      id: 216,
      subject: {
        subjectId: 64,
        subjectCode: "214483",
        subjectName: "Thuong mai dien tu",
      },
      dayOfWeek: 2,
      slotCode: "ca5",
      scheduleType: "CURRENT_TERM",
      location: null,
      note: null,
    },
    {
      id: 217,
      subject: {
        subjectId: 64,
        subjectCode: "214483",
        subjectName: "Thuong mai dien tu",
      },
      dayOfWeek: 3,
      slotCode: "ca2",
      scheduleType: "CURRENT_TERM",
      location: null,
      note: null,
    },
    {
      id: 220,
      subject: {
        subjectId: 66,
        subjectCode: "214987",
        subjectName: "Khoa luan tot nghiep",
      },
      dayOfWeek: 1,
      slotCode: "ca4",
      scheduleType: "CURRENT_TERM",
      location: null,
      note: null,
    },
    {
      id: 219,
      subject: {
        subjectId: 67,
        subjectCode: "214988",
        subjectName: "Tieu luan tot nghiep",
      },
      dayOfWeek: 4,
      slotCode: "ca4",
      scheduleType: "CURRENT_TERM",
      location: null,
      note: null,
    },
    {
      id: 218,
      subject: {
        subjectId: 67,
        subjectCode: "214988",
        subjectName: "Tieu luan tot nghiep",
      },
      dayOfWeek: 6,
      slotCode: "ca5",
      scheduleType: "CURRENT_TERM",
      location: null,
      note: null,
    },
  ],
  success: true,
  message: "User profile loaded successfully",
};

