import type { ScheduleRow, ScheduleStatCard } from "./types";
import { CalendarDays, Clock, PlayCircle, CheckCircle2 } from "lucide-react";

export const mockScheduleStats: ScheduleStatCard[] = [
  {
    title: "Tổng lịch học",
    value: "248",
    change: "+24 tháng này",
    icon: CalendarDays,
  },
  {
    title: "Sắp diễn ra",
    value: "18",
    change: "trong 7 ngày tới",
    icon: Clock,
  },
  {
    title: "Đang diễn ra",
    value: "3",
    change: "ngay bây giờ",
    icon: PlayCircle,
    warning: true,
  },
  {
    title: "Hoàn thành / Đã hủy",
    value: "227",
    change: "91.5% hoàn thành",
    icon: CheckCircle2,
  },
];

export const mockSchedules: ScheduleRow[] = [
  {
    id: 1,
    sessionName: "Ôn tập Giải tích 1 - Chương 5",
    groupName: "Nhóm Toán A1",
    scheduleType: "GROUP",
    creatorName: "Nguyễn Văn An",
    creatorAvatar: null,
    startTime: "2026-06-05T08:00:00",
    endTime: "2026-06-05T10:00:00",
    studyMode: "ONLINE",
    memberCount: 5,
    maxMembers: 8,
    status: "UPCOMING",
    subject: "Giải tích 1",
    description: "Ôn tập chương 5: Tích phân bội, chuẩn bị cho kỳ thi cuối kỳ.",
    location: null,
    onlineLink: "https://meet.google.com/abc-defg-hij",
    members: [
      { userId: 1, fullName: "Nguyễn Văn An", avatarUrl: null },
      { userId: 2, fullName: "Trần Thị Bình", avatarUrl: null },
      { userId: 3, fullName: "Lê Hoàng Cường", avatarUrl: null },
      { userId: 4, fullName: "Phạm Minh Đức", avatarUrl: null },
      { userId: 5, fullName: "Võ Thị Hoa", avatarUrl: null },
    ],
  },
  {
    id: 2,
    sessionName: "Thảo luận CSDL - Normalization",
    groupName: "Cộng đồng CNTT K20",
    scheduleType: "GROUP",
    creatorName: "Trần Bảo Khang",
    creatorAvatar: null,
    startTime: "2026-06-04T14:00:00",
    endTime: "2026-06-04T16:00:00",
    studyMode: "OFFLINE",
    memberCount: 12,
    maxMembers: 20,
    status: "UPCOMING",
    subject: "Cơ sở dữ liệu",
    description: "Thảo luận về các dạng chuẩn hóa: 1NF, 2NF, 3NF, BCNF.",
    location: "Phòng E404 – Tòa E, ĐH Sư phạm Kỹ thuật",
    onlineLink: null,
    members: [
      { userId: 6, fullName: "Trần Bảo Khang", avatarUrl: null },
      { userId: 7, fullName: "Nguyễn Thị Lan", avatarUrl: null },
      { userId: 8, fullName: "Đỗ Quang Minh", avatarUrl: null },
    ],
  },
  {
    id: 3,
    sessionName: "Luyện Speaking IELTS - Topic: Education",
    groupName: null,
    scheduleType: "ONE_ON_ONE",
    creatorName: "Phan Thanh Tài",
    creatorAvatar: null,
    startTime: "2026-06-03T09:00:00",
    endTime: "2026-06-03T10:30:00",
    studyMode: "ONLINE",
    memberCount: 2,
    maxMembers: 2,
    status: "COMPLETED",
    subject: "IELTS Speaking",
    description: "Luyện speaking part 2 & 3 theo chủ đề Education.",
    location: null,
    onlineLink: "https://zoom.us/j/123456789",
    members: [
      { userId: 9, fullName: "Phan Thanh Tài", avatarUrl: null },
      { userId: 10, fullName: "Nguyễn Hữu Nam", avatarUrl: null },
    ],
  },
  {
    id: 4,
    sessionName: "Lab Mạng máy tính - Buổi 3",
    groupName: "Nhóm Lab Mạng",
    scheduleType: "GROUP",
    creatorName: "Lê Quốc Huy",
    creatorAvatar: null,
    startTime: "2026-06-02T13:00:00",
    endTime: "2026-06-02T15:00:00",
    studyMode: "HYBRID",
    memberCount: 7,
    maxMembers: 10,
    status: "COMPLETED",
    subject: "Mạng máy tính",
    description: "Thực hành cấu hình VLAN và Routing trên Cisco Packet Tracer.",
    location: "Phòng Lab F201",
    onlineLink: "https://meet.google.com/xyz-abcd-efg",
    members: [
      { userId: 11, fullName: "Lê Quốc Huy", avatarUrl: null },
      { userId: 12, fullName: "Trần Văn Tùng", avatarUrl: null },
    ],
  },
  {
    id: 5,
    sessionName: "Giải bài tập Xác suất thống kê",
    groupName: "Nhóm Thống kê B2",
    scheduleType: "GROUP",
    creatorName: "Hoàng Minh Tuấn",
    creatorAvatar: null,
    startTime: "2026-06-01T15:00:00",
    endTime: "2026-06-01T17:00:00",
    studyMode: "ONLINE",
    memberCount: 4,
    maxMembers: 6,
    status: "CANCELLED",
    subject: "Xác suất thống kê",
    description:
      "Giải đề thi mẫu chương Biến ngẫu nhiên và Phân phối xác suất.",
    location: null,
    onlineLink: null,
    members: [{ userId: 13, fullName: "Hoàng Minh Tuấn", avatarUrl: null }],
  },
  {
    id: 6,
    sessionName: "Review Code dự án OOP - Sprint 2",
    groupName: "Cộng đồng CNTT K20",
    scheduleType: "GROUP",
    creatorName: "Võ Thành Đạt",
    creatorAvatar: null,
    startTime: "2026-06-06T08:30:00",
    endTime: "2026-06-06T11:00:00",
    studyMode: "OFFLINE",
    memberCount: 6,
    maxMembers: 8,
    status: "UPCOMING",
    subject: "Lập trình hướng đối tượng",
    description:
      "Review code Sprint 2, thảo luận design patterns được sử dụng.",
    location: "Phòng E301 – Tòa E",
    onlineLink: null,
    members: [
      { userId: 14, fullName: "Võ Thành Đạt", avatarUrl: null },
      { userId: 15, fullName: "Nguyễn Thị Mai", avatarUrl: null },
      { userId: 16, fullName: "Trần Đức Anh", avatarUrl: null },
    ],
  },
  {
    id: 7,
    sessionName: "Ôn thi Triết học Mác-Lênin",
    groupName: null,
    scheduleType: "ONE_ON_ONE",
    creatorName: "Đặng Thị Hương",
    creatorAvatar: null,
    startTime: "2026-06-07T19:00:00",
    endTime: "2026-06-07T21:00:00",
    studyMode: "ONLINE",
    memberCount: 2,
    maxMembers: 2,
    status: "UPCOMING",
    subject: "Triết học Mác-Lênin",
    description: "Ôn tập 5 chương trọng tâm, tập trung vào câu hỏi tự luận.",
    location: null,
    onlineLink: "https://meet.google.com/mno-pqrs-tuv",
    members: [
      { userId: 17, fullName: "Đặng Thị Hương", avatarUrl: null },
      { userId: 18, fullName: "Bùi Văn Khanh", avatarUrl: null },
    ],
  },
  {
    id: 8,
    sessionName: "Workshop Git & GitHub cho người mới",
    groupName: "Cộng đồng CNTT K20",
    scheduleType: "GROUP",
    creatorName: "Admin Thầy Chùa",
    creatorAvatar: null,
    startTime: "2026-06-04T17:00:00",
    endTime: "2026-06-04T19:00:00",
    studyMode: "HYBRID",
    memberCount: 15,
    maxMembers: 30,
    status: "UPCOMING",
    subject: "Git & GitHub",
    description:
      "Hướng dẫn sử dụng Git cơ bản, tạo repository, push/pull, merge conflict.",
    location: "Hội trường A101",
    onlineLink: "https://zoom.us/j/workshop-git",
    members: [
      { userId: 19, fullName: "Admin Thầy Chùa", avatarUrl: null },
      { userId: 20, fullName: "Nguyễn Văn Phúc", avatarUrl: null },
    ],
  },
];
